name: Build & Test

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # срабатывает на semver теги: 2.1.0, 2.2.0 и т.д.

jobs:
  build:
    name: Swift Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build \
            -scheme ClickstreamSDK \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO

      - name: Test
        run: |
          xcodebuild test \
            -scheme ClickstreamSDK \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
